apiVersion: apps/v1  # Specifies the API version for the Deployment resource.
kind: Deployment  # Defines the kind of resource as Deployment.
metadata:
  # The name of the Deployment is dynamically set using the release name.
  name: {{ .Release.Name }}-nginx
  labels:
    # The label for the Deployment is dynamically set using the chart name.
    app: {{ .Chart.Name }}
spec:
  # The number of replicas to create for the Deployment is defined in the values.yaml file.
  replicas: {{ .Values.replicaCount }}
  selector:
    # The selector is used to match the labels of the pods to be managed by this Deployment.
    matchLabels:
      app: {{ .Chart.Name }}  # The label to match for the pods.
  template:
    metadata:
      labels:
        # The labels for the pods created by this Deployment are dynamically set using the chart name.
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: nginx  # The name of the container in the pod.
          # The image for the container is dynamically set using the values.yaml file.
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          # The image pull policy is dynamically set using the values.yaml file.
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            # The container will expose port 80 for HTTP traffic.
            - containerPort: 80
