apiVersion: v1
kind: Service
metadata:
  # name is the name of the service, dynamically set using the release name.
  name: {{ .Release.Name }}-nginx
  labels:
    # app label is set to the chart name for identifying the service.
    app: {{ .Chart.Name }}
spec:
  # type defines the type of service. This value is pulled from the values.yaml file.
  type: {{ .Values.service.type }}
  ports:
    - # port defines the port exposed by the service.
      port: {{ .Values.service.port }}
      # targetPort defines the port on the container that the service forwards traffic to.
      targetPort: 80
  # selector specifies the labels that the service uses to select the pods it routes traffic to.
  selector:
    # app label is used to match the pods created by the deployment.
    app: {{ .Chart.Name }}
